### PR TITLE
Issue #37: Resolve MXML from target system by pkg-config when not usi…

### PR DESCRIPTION
**Pull request by bengaineyarm**
…ng vcpkg

### CODE REVIEW

**Comment by clementperon** [comment]
@bengaineyarm the config works fine but the build still fails not related to this MR

```
$> cmake -DENABLE_VCPKG=OFF ..
$> cmake --build . 
/home/clement/work/gator/daemon/BufferUtils.h:6:10: error: 'cstddef' file not found [clang-diagnostic-error]
#include <cstddef>
         ^~~~~~~~~
1 error generated.
```

**Comment by bengaineyarm** [comment]
@clementperon - odd, what compiler (and version) are you using? Possibly this is coming from clang-tidy being enabled by default. Can you reconfigure cmake with the addition of `-DENABLE_CLANG_TIDY_DURING_BUILD=OFF` and let me know if you get the same error.
Not entirely clear why clang-tidy can't find `cstddef` though... its not exactly an unusual header.

**Comment by clementperon** [comment]
> @clementperon - odd, what compiler (and version) are you using? Possibly this is coming from clang-tidy being enabled by default. Can you reconfigure cmake with the addition of `-DENABLE_CLANG_TIDY_DURING_BUILD=OFF` and let me know if you get the same error. Not entirely clear why clang-tidy can't find `cstddef` though... its not exactly an unusual header.

You're right configuring with `-DENABLE_CLANG_TIDY_DURING_BUILD=OFF`  fix the issue
```
$> clang-tidy --version
Ubuntu LLVM version 14.0.0
  
  Optimized build.
  Default target: x86_64-pc-linux-gnu
  Host CPU: znver3
  
$> c++ --version
c++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Review by clementperon — APPROVED** [review]

**Comment by bengaineyarm** [comment]
Thanks @clementperon - I'll make another version, that disables clang-tidy by default to simplify the issue, since sanitizer warnings are mostly my problem rather than yours, then merge that.

Thanks for help testing / validating.

**Pull request merged**
